stages:
  - build
  - test
  - deploy

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - vendor/

composer:5.5:
  stage: build
  tags:
  - shell
  script:
    - composer install --prefer-dist
    
phpunit:5.5:
  stage: test
  tags:
  - shell
  script:
    - ./vendor/bin/phpunit

linting:5.5:
  stage: test
  tags:
  - shell
  script:
    - ./vendor/bin/parallel-lint --exclude vendor .
    - ./vendor/bin/phpcpd ./klink
    - ./vendor/bin/phpcpd --min-lines=25 ./test

composer:7.0:
  image: "docker.klink.asia:5043/alessio/phpunit:7.0"
  stage: build
  tags:
  - docker
  script:
  - composer install --prefer-dist

phpunit:7.0:
  image: "docker.klink.asia:5043/alessio/phpunit:7.0"
  stage: test
  tags:
  - docker
  script:
  - ./vendor/bin/phpunit

linting:7.5:
  image: "docker.klink.asia:5043/alessio/phpunit:7.0"
  stage: test
  script:
    - ./vendor/bin/parallel-lint --exclude vendor .


composer_repo_push:
  stage: deploy
  script:
    - HOME=${SATIS_FOLDER}/comp_home
    - COMPOSER_HOME=${SATIS_FOLDER}/comp_home/.composer
    - GIT_SSL_NO_VERIFY=true
    - cd $SATIS_FOLDER
    - php ./bin/satis build --verbose ./satis.json ./web
  tags: 
  only:
    - tags
