stages:
  - build
  - test
  - deploy

cache:
  key: "$CI_BUILD_REF_NAME"
  group: sharedcache
  paths:
  - vendor/

composer:
  stage: build
  script:
    - composer install --prefer-dist
  only:
    - linting-and-checks
    
phpunit:
  stage: test
  script:
    - ./vendor/bin/phpunit
  only:
    - linting-and-checks


linting:
  stage: test
  script:
    - ./vendor/bin/parallel-lint --exclude vendor .
    - ./vendor/bin/phpcpd ./klink
    - ./vendor/bin/phpcpd ./test
  only:
    - linting-and-checks

unit_test:
  stage: test
  script:
    - composer install --prefer-dist
    - ./vendor/bin/parallel-lint --exclude vendor .
    - ./vendor/bin/phpcpd ./klink && ./vendor/bin/phpcpd ./test
    - ./vendor/bin/phpunit
  tags: 
  only:
    - master

composer_repo_push:
  stage: deploy
  script:
    - HOME=${SATIS_FOLDER}/comp_home
    - COMPOSER_HOME=${SATIS_FOLDER}/comp_home/.composer
    - GIT_SSL_NO_VERIFY=true
    - cd $SATIS_FOLDER
    - php ./bin/satis build --verbose ./satis.json ./web
  tags: 
  only:
    - tags
