stages:
  - build
  - test
  - deploy

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - vendor/

# composer:
#   stage: build
#   script:
#     - composer install --prefer-dist
    
# phpunit:
#   stage: test
#   script:
#     - ./vendor/bin/phpunit

# linting:
#   stage: test
#   script:
#     - ./vendor/bin/parallel-lint --exclude vendor .
#     - ./vendor/bin/phpcpd ./klink
#     - ./vendor/bin/phpcpd --min-lines=25 ./test

build:7.0:
  image: "docker.klink.asia:5043/alessio/phpunit:7.0"
  tags:
  - docker
  script:
  - ls -la
  - composer install --prefer-dist
  # - vendor/bin/phpunit


composer_repo_push:
  stage: deploy
  script:
    - HOME=${SATIS_FOLDER}/comp_home
    - COMPOSER_HOME=${SATIS_FOLDER}/comp_home/.composer
    - GIT_SSL_NO_VERIFY=true
    - cd $SATIS_FOLDER
    - php ./bin/satis build --verbose ./satis.json ./web
  tags: 
  only:
    - tags
