stages:
  - test

cache:
  key: "ksearch-client"
  paths:
  - .composer-cache/

## Making sure that the composer cache folder is the one we have in the CI cache
before_script:
  - export COMPOSER_CACHE_DIR=`pwd`/.composer-cache

# Job templates

.tester_plus_coverage: &tester_plus_coverage
  stage: test
  script:
    - composer install --prefer-dist
    - ./vendor/bin/parallel-lint --exclude vendor .
    - ./vendor/bin/phpunit --verbose --coverage-text --colors=never --coverage-html coverage
  artifacts:
    paths:
    - coverage

# Testing jobs

phpunit:5.6:
  image: "docker.klink.asia/main/docker-php:5.6"
  <<: *tester_plus_coverage
  tags:
  - docker
  

phpunit:7.0:
  image: "docker.klink.asia/main/docker-php:7.0"
  <<: *tester_plus_coverage
  tags:
  - docker
  
phpunit:7.1:
  image: "docker.klink.asia/main/docker-php:7.1"
  <<: *tester_plus_coverage
  tags:
  - docker

