stages:
  - test

cache:
  key: "ksearch-client"
  paths:
  - .composer-cache/

## Making sure that the composer cache folder is the one we have in the CI cache
before_script:
  - export COMPOSER_CACHE_DIR=`pwd`/.composer-cache

## Configuration to run Integration tests
## The configuration is disabled because on the current runners generate services 
## that are not linked together or in the same network
## See https://gitlab.com/gitlab-org/gitlab-runner/issues/2436 and
## https://gitlab.com/gitlab-org/gitlab-runner/issues/1042
# variables:
#   APP_ENV: "dev"
#   APP_DEBUG: "1"
#   SOLRCORE_HOST: "docker.klink.asia-images-k-search-engine"
#   SOLRCORE_NAME: "k-search"
#   KSEARCH_URL: "http://docker.klink.asia-main-k-search/"

# services:
#   - docker.klink.asia/images/k-search-engine:0.2.0
#   - docker.klink.asia/main/k-search:deelop

# Job templates

.tester_plus_coverage: &tester_plus_coverage
  stage: test
  script:
    - composer install --prefer-dist
    - ./vendor/bin/parallel-lint --exclude vendor .
    - ./vendor/bin/phpunit --verbose --coverage-text --colors=never --coverage-html coverage
  artifacts:
    paths:
    - coverage

# Testing jobs

phpunit:5.6:
  image: "docker.klink.asia/main/docker-php:5.6"
  <<: *tester_plus_coverage
  tags:
  - docker
  

phpunit:7.0:
  image: "docker.klink.asia/main/docker-php:7.0"
  <<: *tester_plus_coverage
  tags:
  - docker
  
phpunit:7.1:
  image: "docker.klink.asia/main/docker-php:7.1"
  <<: *tester_plus_coverage
  tags:
  - docker

