stages:
  - build
  - test
  - release

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - vendor/

# Job templates

.builder: &builder
  stage: build
  script:
    - composer install --prefer-dist

.tester: &tester
  stage: test
  script:
    - ./vendor/bin/parallel-lint --exclude vendor .
    - ./vendor/bin/phpcpd ./klink
    - ./vendor/bin/phpcpd --min-lines=25 ./test
    - ./vendor/bin/phpunit

.tester_plus_coverage: &tester_plus_coverage
  stage: test
  script:
    - ./vendor/bin/parallel-lint --exclude vendor .
    - ./vendor/bin/phpcpd ./klink
    - ./vendor/bin/phpcpd --min-lines=25 ./test
    - ./vendor/bin/phpunit --verbose --coverage-text --colors=never --coverage-html coverage
  artifacts:
    paths:
    - coverage



# Build jobs 
# - PHP deps pulling

composer:5.5:
  <<: *builder
  tags:
  - shell

composer:5.6:
  <<: *builder
  image: "docker.klink.asia:5043/klink/php-ci-docker:5.6-alpine"
  tags:
  - docker

composer:7.0:
  <<: *builder
  image: "docker.klink.asia:5043/klink/php-ci-docker:7.0-alpine"
  tags:
  - docker

# Testing jobs

phpunit:5.5:
  <<: *tester
  tags:
  - shell

phpunit:5.6:
  image: "docker.klink.asia:5043/klink/php-ci-docker:5.6"
  <<: *tester_plus_coverage
  tags:
  - docker
  

phpunit:7.0:
  image: "docker.klink.asia:5043/klink/php-ci-docker:7.0-alpine"
  <<: *tester
  tags:
  - docker



# Release as composer managed dependency

push_to_composer_repo:
  stage: release
  script:
    - HOME=${SATIS_FOLDER}/comp_home
    - COMPOSER_HOME=${SATIS_FOLDER}/comp_home/.composer
    - GIT_SSL_NO_VERIFY=true
    - cd $SATIS_FOLDER
    - php ./bin/satis build --verbose ./satis.json ./web
  tags: 
  only:
    - tags
