language: php

services:
  - docker

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - KSEARCH_URL="http://127.0.0.1:8081/"
    - COMPOSER_CACHE_DIR=`pwd`/.composer-cache
  matrix:
    - KSEARCH_TAG="develop" KSEARCH_VERSION="3.6" COMPOSER_FLAGS=""
    - KSEARCH_TAG="v3.6.0-2" KSEARCH_VERSION="3.6" COMPOSER_FLAGS=""

cache:
  directories:
  - ./.composer-cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - sudo service mysql stop
  - docker-compose -f ./tests/docker-compose.yml up -d
  - php ./tests/wait.php

script:
  - ./vendor/bin/parallel-lint --exclude vendor .
  - ./vendor/bin/phpunit

after_script:
  - docker-compose -f ./tests/docker-compose.yml down
