language: php

services:
  - docker

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - KSEARCH_URL="http://127.0.0.1:8080/"
  matrix:
    - KSEARCH_TAG="3.6.0-2" KSEARCH_VERSION="3.7" COMPOSER_FLAGS="--prefer-stable"
    - KSEARCH_TAG="3.6.0-2" KSEARCH_VERSION="3.7" COMPOSER_FLAGS="--prefer-lowest"

cache:
  directories:
  - ./.composer-cache

before_script:
  - export COMPOSER_CACHE_DIR=`pwd`/.composer-cache
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - sudo service mysql stop
  - docker-compose -f ./tests/docker-compose.yml up -d
  - php ./tests/wait.php

script:
  - ./vendor/bin/parallel-lint --exclude vendor .
  - ./vendor/bin/phpunit

after_script:
  - docker-compose -f ./tests/docker-compose.yml down
